[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
shared.workspace = true
bevy_rapier2d.workspace = true
bevy_renet.workspace = true
renet.workspace = true
serde.workspace = true
bincode.workspace = true
